"""harness-evaluator CLI — harness evaluator command line interface."""

from __future__ import annotations

import asyncio
import logging
import sys
import time
from importlib.metadata import version as _pkg_version
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.logging import RichHandler
from rich.panel import Panel
from rich.table import Table

app = typer.Typer(
    name="harness-evaluator",
    help="Harness evaluator: compare agentic coding harnesses on effectiveness and efficiency.",
    no_args_is_help=True,
)
console = Console()


def _get_version() -> str:
    """Return the installed package version."""
    try:
        return _pkg_version("harness-evaluator")
    except Exception:  # noqa: BLE001
        return "unknown"


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"harness-evaluator {_get_version()}")
        raise typer.Exit()


@app.callback()
def main(
    version: bool = typer.Option(  # noqa: ARG001
        None,
        "--version",
        "-V",
        callback=_version_callback,
        is_eager=True,
        help="Show the harness-evaluator version and exit.",
    ),
) -> None:
    """Harness evaluator: compare agentic coding harnesses on effectiveness and efficiency."""


def _configure_logging(verbose: int = 0) -> None:
    """Configure root logging with a RichHandler.

    Levels:
      verbose == 0 → WARNING (quiet; only warnings/errors surface)
      verbose == 1 → INFO (per-cell narrative, gateway per-call capture)
      verbose >= 2 → DEBUG (adapter/docker detail)

    Called inside each command (not at import) so library/test code is not
    affected by CLI logging side effects.
    """
    level = logging.DEBUG if verbose >= 2 else (logging.INFO if verbose >= 1 else logging.WARNING)
    handler = RichHandler(
        console=console,
        show_time=True,
        show_path=verbose >= 2,
        rich_tracebacks=True,
    )
    handler.setLevel(level)
    root = logging.getLogger()
    root.setLevel(level)
    # Replace any prior handlers so repeated invocations in the same process
    # (e.g. tests) do not stack duplicate handlers.
    root.handlers = [handler]


@app.command()
def version() -> None:
    """Print the harness-evaluator version and exit."""
    console.print(f"harness-evaluator {_get_version()}")


@app.command()
def gateway(
    host: str = typer.Option("127.0.0.1", help="Host to bind to"),
    port: int = typer.Option(8877, help="Port to bind to"),
    db: str = typer.Option(
        "harness_evaluator_gateway.db", help="SQLite DB path for captured calls"
    ),
    verbose: int = typer.Option(
        0, "--verbose", "-v", count=True, help="Increase logging verbosity (-v=INFO, -vv=DEBUG)"
    ),
) -> None:
    """Start the gateway proxy server for token accounting."""
    _configure_logging(verbose)
    from harness_evaluator.gateway.proxy import GatewayStartupError, run_proxy

    console.print(f"[bold green]Starting gateway proxy on {host}:{port}[/bold green]")
    console.print(f"Captured calls stored to: {db}")
    console.print(
        "Configure harnesses with:\n"
        f"  ANTHROPIC_BASE_URL=http://{host}:{port}\n"
        f"  OPENAI_BASE_URL=http://{host}:{port}"
    )
    try:
        run_proxy(host=host, port=port, db_path=db)
    except GatewayStartupError as exc:
        console.print("\n[bold red]Error: Cannot start gateway[/bold red]")
        console.print(f"[red]{exc.message}[/red]")
        raise typer.Exit(1) from exc


_STARTER_CONFIG = """\
# harness-evaluator run configuration — generated by `harness-evaluator init`.
# The task library and Docker image default to the versioned bundle, so you
# only need Docker and an API key to get started:
#   docker pull {image}
#   export ANTHROPIC_API_KEY=sk-ant-...
#   harness-evaluator gateway --port 8877     # in a separate terminal
#   harness-evaluator run {filename}
name: "harness-evaluator-first-run"
description: "Minimal starter run — generated by harness-evaluator init"

harnesses:
  - name: opencode
    adapter: opencode
    observability_tier: full
    config:
      mode: agent

models:
  - name: claude-sonnet-4-20250514
    provider: anthropic
    api_key_env: ANTHROPIC_API_KEY
    config:
      max_tokens: 16384

# Task IDs from the bundled library (see `harness-evaluator` docs). Use ["*"] for all 20.
tasks:
  - swe-bugfix-001

repeats: 1
budget_usd: 5.0
gateway_port: 8877
docker_image: "{image}"
parallel_runs: 1
"""


@app.command()
def init(
    filename: str = typer.Option("harness-evaluator.yaml", help="Path for the generated config"),
    force: bool = typer.Option(False, help="Overwrite an existing file"),
) -> None:
    """Scaffold a starter run config in the current directory.

    Lets a new user run harness-evaluator without cloning the repository — the task
    library and runner image default to the bundled/published versions.
    """
    from harness_evaluator.orchestrator.config import default_docker_image

    dest = Path(filename)
    if dest.exists() and not force:
        console.print(f"[red]{filename} already exists.[/red] Use --force to overwrite.")
        raise typer.Exit(1)
    dest.write_text(
        _STARTER_CONFIG.format(image=default_docker_image(), filename=filename),
        encoding="utf-8",
    )
    console.print(f"[bold green]Wrote {filename}[/bold green]")
    console.print(
        "Next:\n"
        f"  docker pull {default_docker_image()}\n"
        "  export ANTHROPIC_API_KEY=sk-ant-...\n"
        "  harness-evaluator gateway --port 8877   # separate terminal\n"
        f"  harness-evaluator run {filename}"
    )


@app.command()
def canary(
    db: str = typer.Option("harness_evaluator_gateway.db", help="SQLite DB path"),
    tolerance_pct: float = typer.Option(
        1.0, "--tolerance-pct", "--tolerance",
        help="Max allowed discrepancy percentage (1.0 = 1%)",
    ),
) -> None:
    """Run the proxy canary: verify token capture accuracy."""
    from harness_evaluator.gateway.canary import run_canary

    result = asyncio.run(run_canary(db_path=db, tolerance_pct=tolerance_pct))
    if result.passed:
        console.print("[bold green]Canary PASSED[/bold green]")
        console.print(result.summary)
    else:
        console.print("[bold red]Canary FAILED[/bold red]")
        console.print(result.summary)
        raise typer.Exit(1)


def _render_progress_panel(
    progress: Any,
    start_time: float,
    budget: float | None,
) -> Panel:
    """Build the live progress Panel for the run command.

    Shows aggregates (bar, done/total/%, counts, cost, elapsed) plus the
    current cell ID (sequential) or running count (parallel).
    """
    elapsed = time.monotonic() - start_time
    done = progress.done
    total = progress.total_cells
    pct = progress.progress_pct

    # Progress bar text
    bar_width = 30
    filled = int(bar_width * done / total) if total else 0
    bar = "█" * filled + "░" * (bar_width - filled)

    # Counts line
    counts = (
        f"[green]✓ {progress.completed}[/green]  "
        f"[red]✗ {progress.failed}[/red]  "
        f"[yellow]⊘ {progress.skipped}[/yellow]  "
        f"[blue]► {progress.running}[/blue]"
    )

    # Cost line
    if budget is not None:
        cost_line = f"Cost: ${progress.total_cost:.4f} / ${budget:.2f}"
    else:
        cost_line = f"Cost: ${progress.total_cost:.4f}"

    # Current cell line
    if progress.running > 0 and progress.current_cell:
        if progress.running == 1:
            cell_line = f"Running: {progress.current_cell}"
        else:
            cell_line = f"Running: {progress.running} cells (last: {progress.current_cell})"
    elif progress.running > 0:
        cell_line = f"Running: {progress.running} cells"
    else:
        cell_line = "Idle"

    content = (
        f"[cyan]{bar}[/cyan]  {done}/{total} ({pct:.1f}%)\n"
        f"{counts}\n"
        f"{cost_line}  |  Elapsed: {elapsed:.0f}s\n"
        f"[dim]{cell_line}[/dim]"
    )
    return Panel(content, title="[bold]Eval Progress[/bold]", border_style="blue")


@app.command()
def run(
    config: str = typer.Argument(..., help="Path to run config YAML file"),
    dry_run: bool = typer.Option(False, help="Print the matrix without executing"),
    check_gateway: bool = typer.Option(
        True, help="Preflight: check that the gateway is reachable before running"
    ),
    verbose: int = typer.Option(
        0, "--verbose", "-v", count=True, help="Increase logging verbosity (-v=INFO, -vv=DEBUG)"
    ),
    show_progress: bool = typer.Option(
        True,
        "--progress/--no-progress",
        help="Show a live progress panel during the run (auto-off in non-TTY)",
    ),
) -> None:
    """Execute an evaluation run from a config file."""
    from rich.live import Live

    from harness_evaluator.orchestrator.config import RunConfig
    from harness_evaluator.orchestrator.engine import Orchestrator, OrchestratorProgress
    from harness_evaluator.orchestrator.results_store import ResultsStore

    config_path = Path(config)
    if not config_path.exists():
        console.print(f"[red]Config file not found: {config}[/red]")
        raise typer.Exit(1)

    cfg = RunConfig.from_yaml(config)
    console.print(f"[bold]Run:[/bold] {cfg.name}")
    console.print(f"  Harnesses: {[h.name for h in cfg.harnesses]}")
    console.print(f"  Models: {[m.name for m in cfg.models]}")
    console.print(f"  Repeats: {cfg.repeats}")

    cells = cfg.build_matrix()
    console.print(f"  Total cells: {len(cells)}")

    if dry_run:
        table = Table(title="Eval Matrix")
        table.add_column("Cell ID")
        table.add_column("Harness")
        table.add_column("Model")
        table.add_column("Task")
        table.add_column("Repeat")
        for cell in cells[:20]:
            table.add_row(
                cell.cell_id, cell.harness.name, cell.model.name, cell.task.id, str(cell.repeat)
            )
        if len(cells) > 20:
            table.add_row("...", "...", "...", "...", "...")
            table.caption = f"Showing 20 of {len(cells)} total cells"
        console.print(table)
        return

    # Preflight: check that the gateway is reachable on the configured port.
    # Connect to 127.0.0.1 (not cfg.gateway_host): gateway_host is the
    # container's view of the host (default "host.docker.internal") and is
    # not resolvable from the CLI process, whereas `harness-evaluator gateway`
    # binds to loopback on this host.
    if check_gateway:
        import socket

        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)
        try:
            sock.connect(("127.0.0.1", cfg.gateway_port))
            sock.close()
            console.print(
                f"[green]Gateway reachable on port {cfg.gateway_port}[/green]"
            )
        except (ConnectionRefusedError, TimeoutError, OSError):
            sock.close()
            console.print(
                f"[red]Gateway is NOT reachable on 127.0.0.1:{cfg.gateway_port}.[/red]\n"
                f"Start it in another terminal with:\n"
                f"  harness-evaluator gateway --port {cfg.gateway_port}\n"
                f"Then re-run this command."
            )
            raise typer.Exit(1) from None

    store = ResultsStore(cfg.results_db)

    # Wire up the Docker runner
    from harness_evaluator.runner.docker import DockerRunner

    runner = DockerRunner(
        image=cfg.docker_image,
        workdir_base=cfg.workdir,
        gateway_host=cfg.gateway_host,
        gateway_port=cfg.gateway_port,
        gateway_db=cfg.gateway_db,
        results_db=cfg.results_db,
    )

    # Check for already-completed cells (resumability) before starting the
    # TUI so the user sees a clear explanation if cells will be skipped.
    completed_cells = store.get_completed_cells(cfg.name)
    if completed_cells:
        console.print(
            f"[yellow]Resuming run '{cfg.name}': {len(completed_cells)} cell(s) "
            f"already completed and will be skipped. "
            f"Use a different run name or delete {cfg.results_db} to start fresh.[/yellow]"
        )

    # Decide whether to show the live TUI.
    # Auto-off in non-TTY (CI, pipes) even if --progress was passed.
    use_tui = show_progress and sys.stdout.isatty()

    progress_result: Any = None

    if use_tui:
        try:
            from harness_evaluator.tui import EvalApp

            app = EvalApp(cfg, store, runner.run_cell, cells)
            app.run()
            progress_result = app.result
        except ImportError:
            # Textual not installed — fall back to Rich Live panel.
            use_tui = False

    if not use_tui and progress_result is None:
        # Rich Live fallback (non-TTY or textual not installed).
        _configure_logging(verbose)
        start_time = time.monotonic()
        latest: list[OrchestratorProgress | None] = [None]

        def on_progress(snapshot: OrchestratorProgress) -> None:
            latest[0] = snapshot

        def render() -> Panel:
            snap = latest[0]
            if snap is None:
                snap = OrchestratorProgress(total_cells=len(cells))
            return _render_progress_panel(snap, start_time, cfg.budget_usd)

        if show_progress and sys.stdout.isatty():
            with Live(render(), console=console, refresh_per_second=4, transient=True):
                orchestrator = Orchestrator(
                    cfg, store, run_cell_fn=runner.run_cell, on_progress=on_progress
                )
                progress_result = asyncio.run(orchestrator.run())
        else:
            orchestrator = Orchestrator(cfg, store, run_cell_fn=runner.run_cell)
            progress_result = asyncio.run(orchestrator.run())

    progress = progress_result

    console.print("\n[bold green]Run complete[/bold green]")
    console.print(f"  Passed: {progress.completed}")
    console.print(f"  Failed: {progress.failed}")
    console.print(f"  Skipped: {progress.skipped}")
    console.print(f"  Cost: ${progress.total_cost:.4f}")

    # Show skip reasons if any cells were skipped
    if progress.skip_reasons:
        console.print(f"\n[yellow]Skipped cells ({len(progress.skip_reasons)}):[/yellow]")
        # Group by reason for conciseness
        from collections import Counter

        reason_counts = Counter(progress.skip_reasons.values())
        for reason, count in reason_counts.most_common():
            console.print(f"  {count} cell(s): {reason}")
        # Show individual cell IDs if 10 or fewer
        if len(progress.skip_reasons) <= 10:
            for cell_id, reason in sorted(progress.skip_reasons.items()):
                console.print(f"    {cell_id}: {reason}")

    # Show first few failures if any
    if progress.errors:
        console.print(f"\n[red]First {min(5, len(progress.errors))} errors:[/red]")
        for err in progress.errors[:5]:
            console.print(f"  {err}")

    # Next steps: tell the user how to explore the results.
    # Pass --db explicitly so the commands work regardless of which
    # directory the user runs them from (results_db may be a custom path).
    console.print("\n[bold]Next steps[/bold]")
    console.print("  [dim]View per-cell results:[/dim]")
    console.print(f"    harness-evaluator results {cfg.name} --db {cfg.results_db}")
    console.print("  [dim]Generate HTML/JSON/CSV reports:[/dim]")
    console.print(f"    harness-evaluator report {cfg.name} --db {cfg.results_db}")
    console.print("  [dim]Statistical analysis:[/dim]")
    console.print(f"    harness-evaluator stats {cfg.name} --db {cfg.results_db}")
    console.print("  [dim]Interactive dashboard:[/dim]")
    console.print(f"    harness-evaluator dashboard --db {cfg.results_db}")


@app.command()
def report(
    run_name: str = typer.Argument(
        None, help="Name of the run to report on (omit to list available runs)"
    ),
    db: str = typer.Option("harness_evaluator_results.db", help="Results DB path"),
    output: str = typer.Option("./reports", help="Output directory for reports"),
) -> None:
    """Generate static reports (HTML, JSON, CSV) for a completed run.

    If no run name is given, lists all runs in the database so you can
    discover the name to use. The run name comes from the ``name:`` field
    in the run config YAML, not the filename.
    """
    from harness_evaluator.orchestrator.results_store import ResultsStore
    from harness_evaluator.reporting.static_report import ReportGenerator

    if not Path(db).exists():
        console.print(f"[red]Results DB not found: {db}[/red]")
        raise typer.Exit(1)

    store = ResultsStore(db)

    # If no run name given, list available runs.
    if run_name is None:
        runs = store.list_runs()
        if not runs:
            console.print(
                "[yellow]No runs found in the database.[/yellow]\n"
                "Run `harness-evaluator run <config.yaml>` first, then use "
                "the `name:` from that config to generate reports."
            )
            raise typer.Exit(1)

        table = Table(title="Available runs")
        table.add_column("Run Name", style="bold")
        table.add_column("Cells", justify="right")
        table.add_column("Completed", justify="right")
        table.add_column("Failed", justify="right")
        table.add_column("Avg Success", justify="right")
        table.add_column("Total Cost", justify="right")

        for r in runs:
            table.add_row(
                r["run_name"],
                str(r["total_cells"]),
                str(r["completed"] or 0),
                str(r["failed"] or 0),
                f"{r['avg_success'] or 0:.2f}",
                f"${r['total_cost'] or 0:.4f}",
            )

        console.print(table)
        console.print(
            "\n[dim]Use `harness-evaluator report <run-name>` to generate "
            "reports.[/dim]"
        )
        raise typer.Exit()

    gen = ReportGenerator(store)
    try:
        paths = gen.generate(run_name, output)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        runs = store.list_runs()
        if runs:
            console.print("\nAvailable runs:")
            for r in runs:
                console.print(f"  {r['run_name']}")
        raise typer.Exit(1) from None

    console.print("[bold green]Reports generated:[/bold green]")
    for fmt, path in paths.items():
        console.print(f"  {fmt}: {path}")


@app.command()
def results(
    run_name: str = typer.Argument(
        None, help="Name of the run to show (omit to list available runs)"
    ),
    db: str = typer.Option("harness_evaluator_results.db", help="Results DB path"),
) -> None:
    """Show results summary for a run in the console.

    If no run name is given, lists all runs in the database so you can
    discover the name to use. The run name comes from the ``name:`` field
    in the run config YAML, not the filename.
    """
    from harness_evaluator.orchestrator.results_store import ResultsStore

    if not Path(db).exists():
        console.print(f"[red]Results DB not found: {db}[/red]")
        raise typer.Exit(1)

    store = ResultsStore(db)

    # If no run name given, list available runs.
    if run_name is None:
        runs = store.list_runs()
        if not runs:
            console.print(
                "[yellow]No runs found in the database.[/yellow]\n"
                "Run `harness-evaluator run <config.yaml>` first, then use "
                "the `name:` from that config to view results."
            )
            raise typer.Exit(1)

        table = Table(title="Available runs")
        table.add_column("Run Name", style="bold")
        table.add_column("Cells", justify="right")
        table.add_column("Completed", justify="right")
        table.add_column("Failed", justify="right")
        table.add_column("Avg Success", justify="right")
        table.add_column("Total Cost", justify="right")

        for r in runs:
            table.add_row(
                r["run_name"],
                str(r["total_cells"]),
                str(r["completed"] or 0),
                str(r["failed"] or 0),
                f"{r['avg_success'] or 0:.2f}",
                f"${r['total_cost'] or 0:.4f}",
            )

        console.print(table)
        console.print(
            "\n[dim]Use `harness-evaluator results <run-name>` to see "
            "per-cell details.[/dim]"
        )
        raise typer.Exit()

    rows = store.get_all_results(run_name)

    if not rows:
        console.print(f"[red]No results found for run '{run_name}'[/red]")
        # Show available runs to help the user.
        runs = store.list_runs()
        if runs:
            console.print("\nAvailable runs:")
            for r in runs:
                console.print(f"  {r['run_name']}")
        raise typer.Exit(1)

    table = Table(title=f"Results: {run_name}")
    table.add_column("Harness")
    table.add_column("Model")
    table.add_column("Task")
    table.add_column("Exit")
    table.add_column("Success")
    table.add_column("Tokens")
    table.add_column("Cost")
    table.add_column("Time(s)")
    table.add_column("Error Class")
    table.add_column("Error Message")

    for r in rows:
        total_tokens = (
            r["input_tokens"]
            + r["output_tokens"]
            + r["cache_read_tokens"]
            + r["cache_write_tokens"]
            + r["reasoning_tokens"]
        )
        error_message = r.get("error_message") or ""
        if len(error_message) > 60:
            error_message = error_message[:60] + "…"
        table.add_row(
            r["harness"],
            r["model"],
            r["task_id"],
            r["exit_class"],
            f"{r['success']:.2f}",
            str(total_tokens),
            f"${r['total_cost']:.6f}",
            f"{r['latency_ms'] / 1000:.1f}",
            r.get("error_class") or "",
            error_message,
        )

    console.print(table)


@app.command()
def adapters() -> None:
    """List available harness adapters and their observability tiers."""
    from harness_evaluator.adapters.registry import list_adapters

    adapter_list = list_adapters()
    if not adapter_list:
        console.print("[red]No adapters registered[/red]")
        return

    table = Table(title="Harness Adapters")
    table.add_column("Name")
    table.add_column("Display Name")
    table.add_column("Observability")
    table.add_column("Description")
    table.add_column("Requires Install")

    for name, info in sorted(adapter_list.items()):
        table.add_row(
            name,
            info.display_name,
            info.observability_tier,
            info.description,
            "Yes" if info.requires_install else "No",
        )

    console.print(table)


@app.command()
def stats(
    run_name: str = typer.Argument(
        None, help="Name of the run to analyze (omit to list available runs)"
    ),
    db: str = typer.Option("harness_evaluator_results.db", help="Results DB path"),
) -> None:
    """Generate statistical analysis for a run.

    If no run name is given, lists all runs in the database so you can
    discover the name to use. The run name comes from the ``name:`` field
    in the run config YAML, not the filename.
    """
    from harness_evaluator.orchestrator.results_store import ResultsStore
    from harness_evaluator.stats import analyze_results

    if not Path(db).exists():
        console.print(f"[red]Results DB not found: {db}[/red]")
        raise typer.Exit(1)

    store = ResultsStore(db)

    # If no run name given, list available runs.
    if run_name is None:
        runs = store.list_runs()
        if not runs:
            console.print(
                "[yellow]No runs found in the database.[/yellow]\n"
                "Run `harness-evaluator run <config.yaml>` first, then use "
                "the `name:` from that config to run statistical analysis."
            )
            raise typer.Exit(1)

        table = Table(title="Available runs")
        table.add_column("Run Name", style="bold")
        table.add_column("Cells", justify="right")
        table.add_column("Completed", justify="right")
        table.add_column("Failed", justify="right")
        table.add_column("Avg Success", justify="right")
        table.add_column("Total Cost", justify="right")

        for r in runs:
            table.add_row(
                r["run_name"],
                str(r["total_cells"]),
                str(r["completed"] or 0),
                str(r["failed"] or 0),
                f"{r['avg_success'] or 0:.2f}",
                f"${r['total_cost'] or 0:.4f}",
            )

        console.print(table)
        console.print(
            "\n[dim]Use `harness-evaluator stats <run-name>` to run "
            "statistical analysis.[/dim]"
        )
        raise typer.Exit()

    results = store.get_all_results(run_name)
    if not results:
        console.print(f"[red]No results found for run '{run_name}'[/red]")
        runs = store.list_runs()
        if runs:
            console.print("\nAvailable runs:")
            for r in runs:
                console.print(f"  {r['run_name']}")
        raise typer.Exit(1)

    console.print(f"\n[bold]Statistical Analysis: {run_name}[/bold]")
    console.print(f"Observations: {len(results)}\n")

    report = analyze_results(results)

    if report.warnings:
        for w in report.warnings:
            console.print(f"[yellow]Warning: {w}[/yellow]")

    # Variance decomposition
    if report.variance_decomposition:
        vd = report.variance_decomposition
        console.print("[bold]Variance Decomposition[/bold]")
        table = Table(show_header=True)
        table.add_column("Component")
        table.add_column("Variance", justify="right")
        table.add_column("% of Total", justify="right")
        table.add_row("Harness", f"{vd.harness_variance:.6f}", f"{vd.harness_pct:.1f}%")
        table.add_row("Model", f"{vd.model_variance:.6f}", f"{vd.model_pct:.1f}%")
        table.add_row("Task", f"{vd.task_variance:.6f}", f"{vd.task_pct:.1f}%")
        table.add_row("Residual", f"{vd.residual_variance:.6f}", f"{vd.residual_pct:.1f}%")
        console.print(table)
        console.print()

    # Mixed-effects model
    if report.mixed_effects and report.mixed_effects.coefficients:
        me = report.mixed_effects
        console.print("[bold]Mixed-Effects Model[/bold]")
        console.print(f"Formula: {me.formula}")
        console.print(f"R²: {me.r_squared:.4f}")
        if me.convergence_warning:
            console.print(f"[red]Warning: {me.convergence_warning}[/red]")
        table = Table(show_header=True)
        table.add_column("Coefficient")
        table.add_column("Estimate", justify="right")
        table.add_column("Std Error", justify="right")
        table.add_column("p-value", justify="right")
        for name, coef in me.coefficients.items():
            se = me.std_errors.get(name, 0)
            p = me.p_values.get(name, 0)
            sig = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else ""))
            table.add_row(name, f"{coef:.6f}", f"{se:.6f}", f"{p:.4f} {sig}")
        console.print(table)
        console.print()

    # Bootstrap CIs
    if report.bootstrap_cis:
        console.print("[bold]Bootstrap 95% CIs (Success by Harness)[/bold]")
        table = Table(show_header=True)
        table.add_column("Harness")
        table.add_column("Mean", justify="right")
        table.add_column("CI Lower", justify="right")
        table.add_column("CI Upper", justify="right")
        for harness, ci in sorted(report.bootstrap_cis.items()):
            table.add_row(
                harness,
                f"{ci.point_estimate:.4f}",
                f"{ci.ci_lower:.4f}",
                f"{ci.ci_upper:.4f}",
            )
        console.print(table)
        console.print()

    # Consistency
    if report.consistency:
        console.print("[bold]Consistency Analysis[/bold]")
        table = Table(show_header=True)
        table.add_column("Harness")
        table.add_column("Model")
        table.add_column("Mean", justify="right")
        table.add_column("Std", justify="right")
        table.add_column("CV", justify="right")
        table.add_column("N", justify="right")
        for c in sorted(report.consistency, key=lambda x: (x.harness, x.model)):
            table.add_row(
                c.harness,
                c.model,
                f"{c.mean_success:.4f}",
                f"{c.std_success:.4f}",
                f"{c.cv_success:.4f}",
                str(c.n_repeats),
            )
        console.print(table)


@app.command()
def dashboard(
    host: str = typer.Option("127.0.0.1", help="Host to bind to"),
    port: int = typer.Option(8080, help="Port to bind to"),
    db: str = typer.Option("harness_evaluator_results.db", help="Results DB path"),
    token: str = typer.Option(
        "",
        "--token",
        envvar="HARNESS_EVALUATOR_DASHBOARD_TOKEN",
        help="Bearer token for authentication. When set, all requests must "
        "include it via Authorization: Bearer <token>, the dashboard_token "
        "cookie (set by /login), or ?token=<token>. Can also be set via the "
        "HARNESS_EVALUATOR_DASHBOARD_TOKEN env var. Recommended when binding "
        "to 0.0.0.0.",
    ),
) -> None:
    """Start the interactive web dashboard."""
    import sqlite3

    import uvicorn

    from harness_evaluator.dashboard.app import create_app

    # Warn (but don't block) when binding to all interfaces without a token.
    if host in ("0.0.0.0", "::") and not token.strip():
        console.print(
            f"[bold yellow]Warning:[/bold yellow] Binding to {host} without --token. "
            "The dashboard has no authentication and will be accessible to "
            "anyone on the network. Consider using --token <secret>."
        )

    auth_token = token or None
    url = f"http://{host}:{port}"

    # Inspect the DB so the user knows whether there is anything to look at
    # before the server starts. A missing or empty database is not fatal — the
    # dashboard renders an empty state — but it is a common source of confusion
    # (e.g. wrong --db path), so we surface it up front.
    db_path = Path(db)
    db_exists = db_path.exists()
    run_count = 0
    if db_exists:
        try:
            with sqlite3.connect(str(db_path)) as conn:
                row = conn.execute(
                    "SELECT COUNT(DISTINCT run_name) FROM run_results"
                ).fetchone()
                run_count = row[0] if row else 0
        except sqlite3.DatabaseError:
            # Corrupt or non-dashboard DB; the app will still try to open it.
            db_exists = False

    # Build the startup panel content.
    db_label = (
        f"[green]{db}[/green]" if db_exists else f"[yellow]{db}[/yellow] (not found)"
    )
    runs_label = (
        f"{run_count} run{'s' if run_count != 1 else ''} available"
        if db_exists and run_count > 0
        else "empty — no runs yet"
        if db_exists
        else "will be created empty"
    )
    auth_label = (
        "[yellow]token required[/yellow]" if auth_token else "[dim]disabled (open)[/dim]"
    )

    lines = [
        f"Database:  {db_label}",
        f"Runs:      {runs_label}",
        f"URL:       [bold]{url}[/bold]",
        f"Auth:      {auth_label}",
        "",
    ]
    if auth_token:
        lines.append(
            f"Browser:   open [link={url}/login]{url}/login[/link] and enter the token"
        )
        lines.append(
            "API:       curl -H 'Authorization: Bearer <token>' "
            f"{url}/api/runs"
        )
    else:
        lines.append(
            f"Browser:   open [link={url}]{url}[/link] to view results"
        )
        lines.append(f"API:       curl {url}/api/runs")
    lines.append("")
    lines.append("[dim]Press Ctrl+C to stop the server.[/dim]")

    console.print(Panel("\n".join(lines), title="[bold]Dashboard[/bold]", border_style="blue"))

    if not db_exists:
        console.print(
            "[dim]Tip: pass --db <path> to point at a results database, "
            "or run `harness-evaluator run <config>` first to populate one.[/dim]"
        )

    app = create_app(results_db=db, token=auth_token)
    # Disable uvicorn access logs when auth is on to avoid leaking the
    # token (the ?token= query param would appear in access log lines).
    uvicorn.run(app, host=host, port=port, access_log=auth_token is None)


@app.command()
def calibrate(
    model: str = typer.Option("claude-sonnet-4-20250514", help="Judge model"),
    calibration_file: str = typer.Option(
        "",
        help="Path to calibration.json (default: config/calibration.json in the project root)",
    ),
) -> None:
    """Run judge calibration against a persistent anchor set."""
    import os

    from harness_evaluator.evaluator.open_ended import (
        DEFAULT_RUBRIC,
        CalibrationSet,
        FrozenJudge,
        JudgeVersion,
    )
    from harness_evaluator.orchestrator.config import TaskSpec, TaskTrack

    # Read API key from environment, not CLI
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        console.print(
            "[red]ANTHROPIC_API_KEY is not set.[/red] Calibration calls the judge "
            "model and requires an API key. Export it and re-run."
        )
        raise typer.Exit(1)

    # Resolve and load the calibration set.
    # Explicit --calibration-file takes precedence; otherwise fall back to
    # the bundled config/calibration.json, then the repo-root config/ dir.
    cal: CalibrationSet
    if calibration_file:
        cal = CalibrationSet.load_from_file(Path(calibration_file))
        console.print(f"[dim]Loaded {len(cal.anchors)} anchors from {calibration_file}[/dim]")
    else:
        import importlib.resources as resources
        import json

        loaded: CalibrationSet | None = None
        try:
            bundled = resources.files("harness_evaluator") / "config" / "calibration.json"
            if bundled.is_file():
                # Read directly from the Traversable to support zipped wheels.
                cal_data = json.loads(bundled.read_text())
                loaded = CalibrationSet()
                loaded.anchors = cal_data.get("anchors", [])
                console.print(
                    f"[dim]Loaded {len(loaded.anchors)} anchors from "
                    f"bundled config/calibration.json[/dim]"
                )
        except (ModuleNotFoundError, AttributeError):
            pass
        if loaded is None:
            # Source-tree fallback: cli.py -> harness_evaluator -> src -> repo.
            fallback = Path(__file__).resolve().parents[2] / "config" / "calibration.json"
            if fallback.exists():
                loaded = CalibrationSet.load_from_file(fallback)
                console.print(
                    f"[dim]Loaded {len(loaded.anchors)} anchors from {fallback}[/dim]"
                )
            else:
                console.print(
                    "[red]Calibration file not found.[/red] "
                    "Create one with `CalibrationSet.save_to_file()` or pass "
                    "--calibration-file <path>."
                )
                raise typer.Exit(1)
        cal = loaded

    # Create a minimal task for calibration
    task = TaskSpec(
        id="calibration",
        name="Calibration Task",
        track=TaskTrack.OPEN_ENDED,
        task_prompt="Implement a caching decorator",
    )

    judge = FrozenJudge(
        version=JudgeVersion.V1_0,
        api_key=api_key,
        model=model,
    )

    console.print("[bold]Running calibration...[/bold]")
    result = asyncio.run(cal.calibrate(judge, task, DEFAULT_RUBRIC))

    console.print(f"\nJudge version: {result['judge_version']}")
    console.print(f"Anchors: {result['num_anchors']}")
    console.print(f"Mean Absolute Error: {result['mean_absolute_error']:.4f}")
    console.print(
        f"Drift detected: {'[red]Yes[/red]' if result['drift_detected'] else '[green]No[/green]'}"
    )
    console.print(
        f"Reliable: {'[green]Yes[/green]' if result['reliable'] else '[red]No[/red]'}"
    )

    for r in result["results"]:
        status = "[green]OK[/green]" if r["success_error"] < 0.15 else "[red]DRIFT[/red]"
        console.print(
            f"  {r['name']}: expected={r['expected_success']:.2f} "
            f"actual={r['actual_success']:.2f} {status}"
        )


if __name__ == "__main__":
    app()
